### ISSUE TITLE
Add JNI

### ISSUE THREAD

**Issue by rintcius** [keynmol/sn-bindgen-examples#35]
Should be fun :)

I had a quick try but it lead to:

```
[bindgen] info Struct 'JNIInvokeInterface_' was detected as having cycles
[bindgen] info Struct 'JNIInvokeInterface_' was detected as having cycles
bindgen.rendering.Error: Failed to resolve aliased definition jobjectRefType
        at bindgen.rendering.Error$.apply(Unknown Source)
        at bindgen.rendering.utils$package$AliasResolver$.create$$anonfun$1$$anonfun$1(Unknown Source)
        at bindgen.rendering.utils$package$AliasResolver$.create$$anonfun$1(Unknown Source)
        at bindgen.rendering.struct$package$.given_AliasResolver$lzyINIT1$1$$anonfun$1(Unknown Source)
        at bindgen.rendering.hack_recursive_structs$package$.go$1$$anonfun$2(Unknown Source)
        at bindgen.rendering.hack_recursive_structs$package$.go$1(Unknown Source)
        at scala.collection.mutable.ListBuffer.map(Unknown Source)
        at bindgen.rendering.hack_recursive_structs$package$.hack_recursive_structs(Unknown Source)
        at bindgen.rendering.struct$package$.struct(Unknown Source)
        at bindgen.rendering.binding$package$.binding$$anonfun$2$$anonfun$9(Unknown Source)
        at bindgen.rendering.binding$package$$$Lambda$39.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure2.apply(Unknown Source)
        at bindgen.rendering.binding$package$.liftedTree1$1(Unknown Source)
        at bindgen.rendering.binding$package$.renderAll$1$$anonfun$1(Unknown Source)
        at bindgen.rendering.binding$package$$$Lambda$26.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at scala.collection.immutable.List.foreach(Unknown Source)
        at bindgen.rendering.binding$package$.binding$$anonfun$2(Unknown Source)
        at bindgen.rendering.binding$package$$$Lambda$2.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at bindgen.rendering.binding$package$.binding(Unknown Source)
        at bindgen.Generate$.main$$anonfun$1(Unknown Source)
        at bindgen.Generate$$$Lambda$1.applyVoid(Unknown Source)
        at scala.runtime.function.JProcedure1.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at <none>.main(Unknown Source)
```

**Comment by keynmol** [comment]
Hah, this would be a fun one, especially if SN finally gains the ability to build dynamic libraries.

The `Failed to resolve aliased definition <..>`  is the bane of my existence - so far I've only seen it on GTK and the JNI header files - and for the life of me I cannot reproduce it in a smaller environment.

**Comment by keynmol** [comment]
2.5 years have passed and I was able to build the bindings and even wrote a blog post about it :) https://blog.indoorvivants.com/2025-02-08-java-from-scala-native-via-jni

This should be easy to port into sn-bindgen-examples: https://github.com/keynmol/scala-native-jni-template/blob/main/build.sbt#L55-L69

**Comment by rintcius** [comment]
🎉 Oh - that's awesome!
